name: Hello World CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        DOCKER_NAMESPACE: ${{secrets.DOCKER_NAMESPACE}}
    - name: Build with Maven
      run: echo ${{secrets.DOCKER_USERNAME}}